### ISSUE TITLE
生成图片格式错误，无法显示

### ISSUE THREAD

**Issue by wnxy** [Yueyang123/LiteCV#1]
![image](https://user-images.githubusercontent.com/38371856/115146937-57de0b00-a08b-11eb-9fd6-90455fac0cd2.png)
win10系统下点击win_build下的任何一个可执行文件生成的图片格式都是损坏的，无法正常打开，也无法查看处理效果

**Comment by Yueyang123** [comment]
你好，在我的个人电脑上直接运行时没有问题的，已经过测试，可能是你运行平台的问题，你可以尝试运行一下BuildWin32构建目录下的IO.exe可执行程序，这个程序主要实现的是各种图片类型的读取与保存。源码目录位于example/basicio/basicio.c 文件夹，可以尝试测试一下




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Yueyang123/LiteCV"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月18日(星期天) 晚上9:17
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Yueyang123/LiteCV] 生成图片格式错误，无法显示 (#1)





 

 win10系统下点击win_build下的任何一个可执行文件生成的图片格式都是损坏的，无法正常打开，也无法查看处理效果

**Comment by wnxy** [comment]
你好，我有些问题想要求教一下您，方便的话加下扣扣：167336314
